# .prettierrc.yml
# see: https://prettier.io/docs/en/options.html
printWidth: 100
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: always
proseWrap: always

# this file is basically used to define how the code should look , but does not throw any errors by itself. the full documentation shows what each option does.
